<<<<<<< HEAD:migrations/versions/a0c46577b38f_df.py
"""df

Revision ID: a0c46577b38f
Revises: 
Create Date: 2022-04-25 01:04:59.208088
=======
"""create flight initialize

Revision ID: 306be565c0ed
Revises: 
Create Date: 2022-04-24 20:19:03.087963
>>>>>>> b32cf95177b96a956fbe4f9245a03635b28e6ec7:migrations/versions/306be565c0ed_create_flight_initialize.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/a0c46577b38f_df.py
revision = 'a0c46577b38f'
=======
revision = '306be565c0ed'
>>>>>>> b32cf95177b96a956fbe4f9245a03635b28e6ec7:migrations/versions/306be565c0ed_create_flight_initialize.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< HEAD:migrations/versions/a0c46577b38f_df.py
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
=======
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('airplane_id', sa.Integer(), nullable=True),
    sa.Column('flight_name', sa.String(), nullable=False),
    sa.Column('depart_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['airplane_id'], ['airplane.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
>>>>>>> b32cf95177b96a956fbe4f9245a03635b28e6ec7:migrations/versions/306be565c0ed_create_flight_initialize.py
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< HEAD:migrations/versions/a0c46577b38f_df.py
    op.drop_table('review')
=======
    op.drop_table('flight')
>>>>>>> b32cf95177b96a956fbe4f9245a03635b28e6ec7:migrations/versions/306be565c0ed_create_flight_initialize.py
    # ### end Alembic commands ###
