"""create flight initialize

Revision ID: 306be565c0ed
Revises: 
Create Date: 2022-04-24 20:19:03.087963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306be565c0ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('airplane_id', sa.Integer(), nullable=True),
    sa.Column('flight_name', sa.String(), nullable=False),
    sa.Column('depart_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['airplane_id'], ['airplane.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight')
    # ### end Alembic commands ###
