<<<<<<< HEAD:migrations/versions/94b492607696_created_route.py
"""created route

Revision ID: 94b492607696
Revises: 
Create Date: 2022-04-22 01:20:07.559345
=======
"""init

Revision ID: 3ec8e843c824
Revises: 
Create Date: 2022-04-22 02:03:39.917792
>>>>>>> main:migrations/versions/3ec8e843c824_init.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/94b492607696_created_route.py
revision = '94b492607696'
=======
revision = '3ec8e843c824'
>>>>>>> main:migrations/versions/3ec8e843c824_init.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< HEAD:migrations/versions/94b492607696_created_route.py
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('duration', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
=======
    op.create_table('airplane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airplane_name', sa.String(), nullable=True),
    sa.Column('airplane_model', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
>>>>>>> main:migrations/versions/3ec8e843c824_init.py
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< HEAD:migrations/versions/94b492607696_created_route.py
    op.drop_table('route')
=======
    op.drop_table('airplane')
>>>>>>> main:migrations/versions/3ec8e843c824_init.py
    # ### end Alembic commands ###
