"""capacity

Revision ID: 737c85cb9ca3
Revises: 3ec8e843c824
Create Date: 2022-04-22 04:10:12.235734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737c85cb9ca3'
down_revision = '3ec8e843c824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airplane', sa.Column('passenger_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airplane', 'passenger_capacity')
    # ### end Alembic commands ###
