"""added flight class and reservation relationship

Revision ID: b1e1c38a92ae
Revises: 81038f6837aa
Create Date: 2022-05-07 18:38:21.407907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e1c38a92ae'
down_revision = '81038f6837aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('flight_class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reservation', 'flight_class', ['flight_class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'flight_class_id')
    # ### end Alembic commands ###
